package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// 方块属性状态生成：为运行时需要“按属性查询状态 ID”的方块生成完整状态表
// （红石线、拉杆、按钮、红石灯/火把、传送门、双格植物等）。
//
// 与 block_shapes_generated.go 不同：形状表覆盖全部方块但只保留碰撞信息；
// 本表只覆盖少量方块但保留全部属性（运行时用 BlockStateWithProps 按属性
// 匹配状态 ID）。新增需要按属性查询的方块时，把它加入 propStateBlocks 并
// 重新运行生成器。
//
// 生成产物：internal/registry/block_states_generated.go。

// propStateBlocks 是需要生成属性状态表的方块列表（按名称排序输出）。
var propStateBlocks = []string{
	"minecraft:end_portal_frame",
	"minecraft:lever",
	"minecraft:lilac",
	"minecraft:nether_portal",
	"minecraft:oak_button",
	"minecraft:peony",
	"minecraft:redstone_block",
	"minecraft:redstone_lamp",
	"minecraft:redstone_torch",
	"minecraft:redstone_wall_torch",
	"minecraft:redstone_wire",
	"minecraft:rose_bush",
	"minecraft:stone_button",
	"minecraft:sunflower",
}

// writeBlockPropertyStates 生成方块属性状态表。
func writeBlockPropertyStates(outDir, version string, blocks map[string]blockShapeData) error {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by tools/genregistries from Minecraft %s reports/blocks.json; DO NOT EDIT.\n", version)
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// 需要按属性查询的方块状态表（红石、传送门、双格植物等）。\n")
	fmt.Fprintf(&b, "// 运行时使用 registry.BlockStateWithProps 按属性匹配状态 ID；\n")
	fmt.Fprintf(&b, "// 需要新方块时修改 tools/genregistries/blockstates.go 的 propStateBlocks。\n")
	fmt.Fprintf(&b, "\npackage registry\n\n")

	names := append([]string(nil), propStateBlocks...)
	sort.Strings(names)
	missing := make([]string, 0)
	total := 0
	fmt.Fprintf(&b, "// BlockPropertyStates 是参与属性匹配的方块的全部状态。\n")
	fmt.Fprintf(&b, "var BlockPropertyStates = map[string][]PropertyState{\n")
	for _, name := range names {
		data, ok := blocks[name]
		if !ok {
			missing = append(missing, name)
			continue
		}
		states := append([]stateShapeData(nil), data.states...)
		sort.Slice(states, func(i, j int) bool { return states[i].id < states[j].id })
		fmt.Fprintf(&b, "\t%q: {\n", name)
		for _, state := range states {
			keys := make([]string, 0, len(state.props))
			for key := range state.props {
				keys = append(keys, key)
			}
			sort.Strings(keys)
			parts := make([]string, 0, len(keys))
			for _, key := range keys {
				parts = append(parts, fmt.Sprintf("%q: %q", key, state.props[key]))
			}
			fmt.Fprintf(&b, "\t\t{ID: %d, Props: map[string]string{%s}},\n", state.id, strings.Join(parts, ", "))
		}
		fmt.Fprintf(&b, "\t},\n")
		total += len(states)
	}
	fmt.Fprintf(&b, "}\n")
	if len(missing) > 0 {
		return fmt.Errorf("blocks.json 缺少方块：%s", strings.Join(missing, "、"))
	}

	source := []byte(b.String())
	formatted, err := format.Source(source)
	if err != nil {
		return fmt.Errorf("格式化生成代码：%w（原始内容长度 %d）", err, len(source))
	}
	path := filepath.Join(outDir, "block_states_generated.go")
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		return err
	}
	fmt.Printf("已生成方块属性状态表（%d 个方块、%d 个状态）\n", len(names), total)
	return nil
}
